version: '3.8'

services:
  account-service:
    image: account-service:latest
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      # Postgres connection
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: account_db

      # Redis Connection
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_JAAS_USERNAME: ${SPRING_KAFKA_JAAS_USERNAME}
      SPRING_KAFKA_JAAS_PASSWORD: ${SPRING_KAFKA_JAAS_PASSWORD}
      JAVA_TOOL_OPTIONS: "-Xms192m -Xmx256m"
    mem_limit: 400m
    networks:
      - banking-network

  transaction-service:
    image: transaction-service:latest
    container_name: transaction-service
    ports:
      - "8082:8082"
    environment:
      # Postgres connection
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: transaction_db

      # Redis Connection
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_JAAS_USERNAME: ${SPRING_KAFKA_JAAS_USERNAME}
      SPRING_KAFKA_JAAS_PASSWORD: ${SPRING_KAFKA_JAAS_PASSWORD}
      ACCOUNT_SERVICE_URL: http://account-service:8081
      JAVA_TOOL_OPTIONS: "-Xms192m -Xmx256m"
    mem_limit: 400m
    depends_on:
      account-service:
        condition: service_started
    networks:
      - banking-network

  fraud-detection-service:
    image: fraud-detection-service:latest
    container_name: fraud-detection-service
    ports:
      - "8083:8083"
    environment:
      # Redis Connection
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}
      #Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_JAAS_USERNAME: ${SPRING_KAFKA_JAAS_USERNAME}
      SPRING_KAFKA_JAAS_PASSWORD: ${SPRING_KAFKA_JAAS_PASSWORD}
      ACCOUNT_SERVICE_URL: http://account-service:8081
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx192m"
    mem_limit: 350m
    depends_on:
      account-service:
        condition: service_started
    networks:
      - banking-network

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      # Redis Connection
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}
      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_JAAS_USERNAME: ${SPRING_KAFKA_JAAS_USERNAME}
      SPRING_KAFKA_JAAS_PASSWORD: ${SPRING_KAFKA_JAAS_PASSWORD}
      ACCOUNT_SERVICE_URL: http://account-service:8081
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx192m"
    mem_limit: 350m
    depends_on:
      account-service:
        condition: service_started
    networks:
      - banking-network

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      # Postgres connection
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: payment_db
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      RAZORPAY_WEBHOOK_SECRET: ${RAZORPAY_WEBHOOK_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_KAFKA_JAAS_USERNAME: ${SPRING_KAFKA_JAAS_USERNAME}
      SPRING_KAFKA_JAAS_PASSWORD: ${SPRING_KAFKA_JAAS_PASSWORD}
      JAVA_TOOL_OPTIONS: "-Xms192m -Xmx256m"
    mem_limit: 400m
    networks:
      - banking-network

  api-gateway:
    image: api-gateway:lastest
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      # Redis Connection
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}

      ACCOUNT_SERVICE_URL: http://account-service:8081
      TRANSACTION_SERVICE_URL: http://transaction-service:8082
      PAYMENT_SERVICE_URL: http://payment-service:8084
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx192m"
    mem_limit: 350m
    depends_on:
      account-service:
        condition: service_started
      transaction-service:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge